import {Inter} from 'next/font/google'
import './globals.css'
import Header from '@/layout/header/Header'
import {Toaster} from '@/components/ui/sonner'
import Script from 'next/script'

const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: 'Đặt bàn ăn',
  description: 'Generated by FINN IT',
}

export default function RootLayout({children}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        <div className='pt-[8rem] max-md:pt-[5rem]'>{children}</div>
        <Toaster richColors />
        <Script
          strategy='lazyOnload'
          src={`https://www.googletagmanager.com/gtag/js?id=GTM-5S45KWGT`}
        ></Script>
        <Script strategy='lazyOnload'>
          {`window.dataLayer = window.dataLayer || [];
							function gtag(){dataLayer.push(arguments);}
							gtag('js', new Date());
							gtag('config', 'GTM-5S45KWGT');`}
        </Script>
      </body>
    </html>
  )
}
